---
- name: Generate Documentation
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    output_directory: "./files/working_docs/"
    source_directory: "./templates/docs/"
    doc_directory: "./files/pandoc_generated/"
    reference: "./files/pandoc_reference/reference.docx"
    templates_list:
      - { src: "{{ source_directory }}satellite_runbook_governance.j2",
        dest: "{{ output_directory }}satellite_runbook_governance.md",
        doc: "{{ doc_directory }}satellite_runbook_governance.docx" }
      - { src: "{{ source_directory }}aap_operations_manual.j2",
        dest: "{{ output_directory }}aap_operations_manual.md",
        doc: "{{ doc_directory }}aap_operations_manual.docx" }
      - { src: "{{ source_directory }}aap_platform_admin_guide.j2",
        dest: "{{ output_directory }}aap_platform_admin_guide.md",
        doc: "{{ doc_directory }}aap_platform_admin_guide.docx" }
      - { src: "{{ source_directory }}aap_policy_governance.j2",
        dest: "{{ output_directory }}aap_policy_governance.md",
        doc: "{{ doc_directory }}aap_policy_governance.docx" }
      - { src: "{{ source_directory }}aap_platform_runbook.md.j2",
        dest: "{{ output_directory }}aap_platform_runbook.md",
        doc: "{{ doc_directory }}aap_platform_runbook.docx" }
  tasks:
    - name: Load common variables
      include_vars: global/aap.yml

    - name: Checking my sanity, Debug all AAP variables
      debug:
        msg: "{{ item }} = {{ vars[item] | default('MISSING VALUE') }}"
      loop: "{{ vars.keys() | list | select('match', '^AAP_.*') | list }}"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]

    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ output_directory }}"
        state: directory
        mode: '0755'

    - name: Debug template list items to render to Markdown files
      debug:
        msg: "{{ item }}"
      loop: "{{ templates_list }}"

    - name: Render templates to Markdown files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop: "{{ templates_list }}"
      loop_control: {}
      when: 
        - item.dest | default('') | length > 0

    - name: Convert Markdown to DOCX
      ansible.builtin.command:
        cmd: > 
          pandoc 
          --to=docx 
          --lua-filter=lua/pagebreak.lua 
          --lua-filter=lua/codeblock.lua 
          --lua-filter=lua/linebreak.lua
          --reference-doc="{{ reference }}" 
          --toc 
          "{{ item.dest }}" 
          -o "{{ item.doc }}"
      loop: "{{ templates_list }}"
      when: 
        - item.dest | default('') | length > 0
